### ISSUE TITLE
PHP Fatal error, 500 Server Error [Help Wanted][Newbie]

### ISSUE THREAD

**Issue by drjagan** [EntradaProject/entrada-1x#4]
Hello, 

Congratulations on the 1.8.0 release!

I tried to follow instructions on [First time installation](https://github.com/EntradaProject/entrada-1x/wiki/First-time-installation). 

On launching setup, I got a Server 500 error. 
The Apache2 logs showed the following: 
`PHP Fatal error:  Uncaught Error: Class 'Entrada_Setup' not found in /var/www/html/entrada-me-1.8.0-open-edition/setup/index.php:287\nStack trace:\n#0 {main}\n  thrown in /var/www/html/entrada-me-1.8.0-open-edition/setup/index.php on line 287`

The line 287 in setup/index.php probably refers to: `$setup = new Entrada_Setup($PROCESSED); `

I have no idea how to proceed further. 
Is there anything I can do to resolve this error please?

Thank you for all the assistance.

----
Also, on a side note, the first hurdle I had to overcome (as a newbie) was that composer.json file was missing in the 'entrada-1x-entrada-me-1.8.0-open' folder. I manually copied the file in the zip file to the folder and was able to complete the installation. This, I assume might be quite at par for those with experience, but I suppose newbies might appreciate to know in the installation notes?

**Comment by mattsimpson** [comment]
Thank you very much Dr. Jagen.

`Entrada_Setup` should be autoloaded by Composer. It appears that the `composer.json` file is missing from the archive that you downloaded, which now that you mention it, is an entirely separate issue. I have deleted that tar.gz file you would have downloaded, and instead recommend just relying on the one provided by GitHub:

https://github.com/EntradaProject/entrada-1x/archive/entrada-me-1.8.0-open.tar.gz

I hope that helps.
