### ISSUE TITLE
The absolute path you have provided for the Entrada Storage Path does not not exist. Please ensure this directory exists and that all folders within it can be written to by PHP.

### ISSUE THREAD

**Issue by snipersp** [EntradaProject/entrada-1x#5]
The absolute path you have provided for the Entrada Storage Path does not not exist. Please ensure this directory exists and that all folders within it can be written to by PHP. Setup does not recognize any given path to the storage folder. please advice. thks.

**Comment by mattsimpson** [comment]
Sure thing. You would need to chmod to the directories within the `www-root/core/storage` folder to 777 in order to allow Apache to write to them. Either that, or change the owner of directories to the user that Apache is running as.

Sincerely,
Matt Simpson
