### ISSUE TITLE
All links giving a 404

### ISSUE THREAD

**Issue by michaelfariborz** [EntradaProject/entrada-1x#8]
I have set up a virtual machine (Oracle VirtualBox) with LAMP (Centos 7.4.1708, httpd 2.4.6-67, MariaDB 5.5.56, PHP 7.1.12), downloaded the entrada-1x project and placed it in the /var/www/html/Sites/ directory.  I then went through the setup steps and can sign in as an administrator, which takes me to the Dashboard.  However, when I click any of the links in the menu, I get a 404 error. (The requested URL /Sites/entrada-1x/www-root/courses was not found on this server.)

I'm assuming I am missing something, perhaps a PHP related module, but I have no idea what it is.  If someone could point me in the right direction, I would appreciate it.

**Comment by mattsimpson** [comment]
Hello Michael,

This is likely because the `.htaccess` file is missing from the `www-root` directory or it does not contain the necessary directives. If you've setup an Apache virtualhost it would look like:

```
RedirectMatch 404 /\\.git(/|$)

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /

	RewriteCond %{HTTP:Authorization} ^(.*)
	RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

	RewriteCond %{REQUEST_FILENAME} -f [OR]
	RewriteCond %{REQUEST_FILENAME} -l [OR]
	RewriteCond %{REQUEST_FILENAME} -d
	RewriteRule ^.* - [L,QSA]

# Default Entrada Rules
	RewriteRule ^api/v2/(.*)$ api/v2/index.php/$1 [L,QSA]
	RewriteRule ^admin/(.*)$ admin.php/$1 [L,QSA]

	RewriteRule ^community$ index.php/communities [L,QSA]
	RewriteRule ^community/feeds(.*)$ community/serve-feeds.php$1 [L,QSA]
	RewriteRule ^community/(.*)$ community/index.php/$1 [L,QSA]

	RewriteRule ^images/dynamic/(.*)$ serve-images.php/$1 [L,QSA]
	RewriteRule ^notices/(.*)$ serve-notices.php?g=$1 [L,QSA]
	RewriteRule ^rss$ serve-rss.php [L,QSA]
	RewriteRule ^rss/(.*)$ serve-rss.php/$1 [L,QSA]
	RewriteRule ^podcasts/(.*)$ serve-podcasts.php?request=$1 [L,QSA]
	RewriteRule ^calendars/(.*)$ api/calendar.api.php?request=$1 [L,QSA]

	RewriteRule ^(.*)$ index.php/$1 [L,QSA]
</IfModule>
```

**Comment by michaelfariborz** [comment]
Thanks Matt,

Turns out the AllowOverride was set to None in my <Directory "/var/www/html"> entry in my /etc/httpd/conf/http.conf file.  Once I switched it to All, things began to work.  I would have never thought to look there if you hadn't pointed out the .htaccess file.

Thank you for your help!

**Comment by mattsimpson** [comment]
You're very welcome.

Just one simple note: Entrada ME 1.9 is a bit "behind the times". We've come a long way in Entrada ME 1.10 and 1.11, which do not presently have an Open Edition (sorry about that). If you need any details or further information. Please don't hesitate to reach out.

Sincerely, Matt Simpson
